name: Build CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

<<<<<<< HEAD
      # TODO 01 - Add a step to run tests
      - name: Run tests
        run: go test ./...

  compile:
    needs: test
=======
      - name: Run tests
        run: go test ./...
  
  compile:
    needs: test
    if: success()
>>>>>>> 027a9252fc022d095d876be36889d3653e141052

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Compile binary
	run: go build -o myapp
